spring:
  application:
    name: graphql-spring-boot
  graphql:
    graphiql:
      enabled: true
    path: /api/graphql

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

app:
  graphql:
    baseurl: "http://localhost:8080/api/graphql"